<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PHP Hound Results</title>
    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.deep_purple-purple.min.css" /> 
    <script src="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <style>
    .mdl-card {
      margin: 16px;
      min-height: 0;
      width: auto;
    }

    .mdl-card__title {
      background-color: rgb(103,58,183);
      color: #fff;
    }

    .mdl-card__supporting-text p:last-child {
      margin-bottom: 0;
    }
    </style>
  </head>
  <body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header mdl-color--primary">
        <div class="mdl-layout__header-row">
          <h3>PHP Hound</h3>
        </div>
      </header>
      <main class="mdl-layout__content">

        <?php foreach ($result as $fileName => $lines) : ?>
        <div class="mdl-card mdl-shadow--2dp">
          <div class="mdl-card__title">
            <h2 class="mdl-card__title-text"><?= $fileName ?></h2>
          </div>
          <div class="mdl-card__supporting-text">
            <?php foreach ($lines as $lineNumber => $issues) : ?>
            <?php foreach ($issues as $issue) : ?>
            <p>
              <strong><?= $lineNumber ?></strong>:
              <?= $issue['message'] ?>
            </p>
            <?php endforeach; ?>
            <?php endforeach; ?>
          </div>
        </div>
        <?php endforeach; ?>

        <footer class="mdl-mega-footer">
          <div class="mdl-mega-footer--bottom-section">
            <div class="mdl-logo">
              Generated by <a href="https://github.com/alanwillms/php-hound"><?=
              $this->e($phpHoundVersion)
              ?></a>
              using <a href="http://php.net/"><?=
              $this->e($phpVersion)
              ?></a>
              at <?= $this->e($generationTime) ?>.
            </div>
          </div>
        </footer>
      </main>
    </div>
  </body>
</html>